### ISSUE TITLE
Загрузка фотографий пользователей

### ISSUE THREAD

**Issue by LisyaVostokova** [dimmarch/web-surveys#16]
Сейчас выдаёт множество ошибок.
Нужна возможность загрузки фотографий (указывать им место на сервере для хранения что ли)

**Comment by dimmarch** [comment]
- [ ] удаление фото

- [ ] окошко "Фото успешно загружено"

- [ ] обновление страницы после загрузки фото (может неполучиться)

- [ ] показывать ошибку (по аналогии с handleAvatarSuccess - посмотреть в документации)
