### ISSUE TITLE
при очищении ответов перестает работать автозполнение

### ISSUE THREAD

**Issue by dimmarch** [dimmarch/web-surveys#47]
-перейти на страницу /admin/answers
-нажать на поле ввода "Пользователь". Убедиться, что предлагается список пользователей
-выбрать любую анкету в поле ввода "Название анкеты"
-очистить выбор анкеты нажатием крестика в этом же поле ввода
-снова переместить курсор на поле ввода "Пользователь"
**Ожидаемый результат:**
появляется список пользователей
**Текущий результат:**
список пользователей не появляется

**Comment by LisyaVostokova** [comment]
Поправила.
